judofyr/temple

- README.md
Hi!
On second thoughts, I think a very small improvement could be made by enhancing the visibility of EXPRESSIONS.md  + documentation.
On a more general tone, possibly one reason I didn't consider using much filters and generators in wlang was due to the high cost of reading through the source code to find what already existed. The README mostly contains an introduction to temple principles. As soon as you decide to rely it, what you definitely need is:
1) a list of standard abstractions (hence the first commit)
2) a list + good documentation of every filter and every generator available.
I think 2) is still completely missing (?). In addition, 1) and 2) should have much more visibility. This patch only starts that discussion.
> Enhance visibility of the EXPRESSIONS.md file (+ wlang link)

- lib/temple/filters/remove_bom.rb
- lib/temple/generator.rb
- lib/temple/generators/rails_output_buffer.rb
- lib/temple/html/pretty.rb
- lib/temple/mixins/dispatcher.rb
- lib/temple/utils.rb
Used https://github.com/schneems/let_it_go to find easy places for `String#freeze` optimization. 
This patch reduces the number of strings allocated on EVERY request by 1040.
I used codetriage.com (which uses slim) to test.
> Freeze non-mutated string literals

- lib/temple/generators/array_buffer.rb
- lib/temple/generators/erb.rb
- test/test_generator.rb
`Array#join` is equivalent to `Array#join($,)` . Explicitly give an
empty string in order to avoid `$,` effect.
> Generators should not be affected by `$,` value

- lib/temple/mixins/dispatcher.rb
It'll be easier to understand what's going on with pry, and there will be no blank `(eval)` lines in backtraces.
> Save location for compiled dispatcher method

- .travis.yml
- gemfiles/Gemfile.escape_utils
- gemfiles/Gemfile.escape_utils.lock
- lib/temple/utils.rb
Added in support for Ruby 2.3 native CGI.escapeHTML method.
#97
> Add support for Ruby 2.3 native CGI.escapeHTML

- lib/temple/filters/string_splitter.rb
- test/filters/test_string_splitter.rb
A trivial fix for https://github.com/judofyr/temple/pull/96. I want StringSplitter to raise named exception like Hamlit's original one.
> Name exceptions in StringSplitter

- lib/temple/filters/static_analyzer.rb
I fixed a following warning introduced in https://github.com/judofyr/temple/pull/95. I hope this will be released as v0.7.8.
```
temple/lib/temple/filters/static_analyzer.rb:38: warning: assigned but unused variable - col
```
By the way, Haml's master uses Temple now! :beer:
> Fix a warning in StaticAnalyzer

- CHANGES
- lib/temple.rb
- lib/temple/filters/static_analyzer.rb
- lib/temple/static_analyzer.rb
- test/filters/test_static_analyzer.rb
- test/test_static_analyzer.rb
I have this kind of utility in both Hamlit and new Haml branch. I haven't used these methods (Of course I use the Temple filter itself.) from Hamlit because I put this in deep namespace in https://github.com/judofyr/temple/pull/95. Now I need to reinvent this in Haml too.
Since this is also convenient for template engine's language-specific optimization, I want to make this tool available globally. Also, I added `.available?` method to check availability easily.
> Carve out Temple::StaticAnalyzer from Temple::Filters::StaticAnalyzer

- lib/temple/mixins/dispatcher.rb
This is the minimum change necessary to allow Roda's specs to work,
there may be other cases that need to be fixed for
--enable-frozen-string-literal to work.
> Fix issue with --enable-frozen-string-literal

- lib/temple/templates/rails.rb
Running Temple in Rails 6 triggers a deprecation warning:
```
DEPRECATION WARNING: Single arity template handlers are deprecated.  Template handlers must
now accept two parameters, the view object and the source for the view object.
Change:
>> #<Class:0x000000010f6c1c80>#call(template)
To:
>> #<Class:0x000000010f6c1c80>#call(template, source)
```
This is because of a recent change to Rails (https://github.com/rails/rails/pull/35119) that attempts to make template handlers read-only.
This PR removes the deprecated (“old-style”) handler for Rails 6 projects, while maintaining compatibility with older versions of Rails (3.1-5.2).
> Update Rails template for 6.0

- lib/temple/mixins/grammar_dsl.rb
In `Temple::Mixins::GrammerDSL::Value#Rule`, call `=~` method to `Class` class then that causes a warning message.
This behavior introduced from ruby 2.6 with `-W` option.
(And ruby 2.7 always show a warning message)
https://bugs.ruby-lang.org/issues/15231
https://github.com/ruby/ruby/commit/ebff9dc10
~Therefore if "elem" is `Class` class, skip calling `=~` method.~
Therefore use case-when-else clause to avoid warning.
> Suppress deprecated warning by Object#=~ since ruby 2.6

- lib/temple/generator.rb
Currently when you want to always use ArrayBuffer generator, you must define it like this:
Engine.new(generator: Generators::ArrayBuffer.new(capture_generator: 'ArrayBuffer'))
I’d expect that `ArrayBuffer` will implicitly use `ArrayBuffer` even for captures, not `StringBuffer`. The current behaviour is IMO very confusing and inconvenient.
This commit changes the default :capture_generator to `self`, i.e. the same type of generator will be used for captures by default.
Engine.new(generator: Generators::ArrayBuffer)
> Change default :capture_generator to self

- .travis.yml
Noticed that many of the ruby versions tested are past end of life
It looked like `ESCAPE_UTILS=1` was building native extensions, so I excluded that for jruby.
The previous travis.yml file was doing something similar.
> update ruby test version

- lib/temple/templates/tilt.rb
https://github.com/rtomayko/tilt/blob/master/lib/tilt/template.rb
Tilt templates now prefer using metadata[:mime_type] to expose the mime type of a template. This is causing templates like slim to not have a mime type in the metadata, although it can still be accessed through the depreciated default_mime_type
> Fixed depreciated tilt template mime type

- lib/temple.rb
- lib/temple/filters/ambles.rb
- lib/temple/templates/rails.rb
An alternative patch for https://github.com/judofyr/temple/pull/133. Note that, with this patch, temple users need to `use :Ambles` in the engine to let `Temple::Templates::Rails` support the behavior.
> Support annotate_rendered_view_with_filenames

- lib/temple/utils.rb
👋 Hello!
In the latest release of EscapeUtils there is a [deprecation warning](https://github.com/brianmario/escape_utils/blob/df753cca15d284ff0273bdb418d6506af26d4fff/lib/escape_utils.rb#L43) and the method just calls CGI.escapeHTML so there is no need to call EscapeUtils anymore.
> Drop EscapeUtils.escape_html

- lib/temple/generators/rails_output_buffer.rb
- test/test_generator.rb
In https://github.com/rails/rails/pull/45614 I modified `ActionView::OutputBuffer` to no longer be a subclass of `ActiveSupport::SafeBuffer` and as such it's not recommended to use `SafeBuffer` for buffering views anymore.
Additionally in https://github.com/rails/rails/pull/45731 I start doing some changes so that we stop mutating `@output_buffer`. So template should no longer assign `@output_buffer` themselves.
> Improve compatibility with upcoming Rails 7.1

- lib/temple/filters/string_splitter.rb
- test/filters/test_string_splitter.rb
`StringSplitter` splits a string literal `%Q(href("#{1 + 1}");)` into `%Q(href()`, `1 + 1`, and `%Q();)`. 
Because `%Q(` `)` was used for quoting the string and the string content also has parenthesis, it results in `unterminated string meets end of file (SyntaxError)`.
To extract `"href("` safely, we should just use a null character for quoting a string to be `eval`ed.
> Fix a crash in StringSplitter filter

- lib/temple/generator.rb
- spec/generator_spec.rb
Pass the configured captured_generator (along with all other top-level engine options) when initializing each capture_generator for handling `:capture` sexps. This ensures that nested captures behave consistently for the given top-level engine configuration.
This is the same diff from #112, but opened as a fresh PR over the current master branch.
See discussion in #112 for the various issues this fixes.
> Use same capture_generator across nested captures

- .github/workflows/test.yml
This PR adds Ruby 3.3 to CI matrix and updates checkout action version
> Add Ruby 3.3 to CI matrix. Updates checkout action version
